history = 10
history_file_path = "config/.massa_history"
timeout = 1000

[default_node]
ip = "127.0.0.1"
private_port = 33034
public_port = 33035

[http]
    # maximum size in bytes of a request
    max_request_body_size = 52428800
    # request timeout
    request_timeout = 60000
    # maximum number of outcoming connections allowed
    max_concurrent_requests = 100
    # certificate_store, `Native` or `WebPki`
    certificate_store = "Native"
    # JSON-RPC request object id data type, `String` or `Number` 
    id_kind = "Number"
    # max length for logging for requests and responses. Logs bigger than this limit will be truncated
    max_log_length = 4096
    # custom headers passed to the server with every request (default is empty).
    headers = []
